import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { AppHeader } from '@/components/AppHeader';
import { Screen } from '@/components/Screen';
import { useMockStore } from '@/context/MockStoreContext';
import { locations, products, suppliers } from '@/mock/data';
import { useColors } from '@/hooks/useColors';

export default function StockInHistoryScreen() {
  const colors = useColors();
  const { stockIns } = useMockStore();
  return <Screen><AppHeader title="Stock In history" subtitle={`${stockIns.length} local receiving records`} /><Pressable onPress={() => router.push('/stock/in-new' as never)} style={({ pressed }) => [{ height: 55, borderRadius: 16, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 18 }, pressed && { opacity: 0.75 }]}><Feather name="plus-circle" size={19} color={colors.white} /><Text style={{ color: colors.white, fontFamily: 'Inter_700Bold', fontSize: 14 }}>NEW STOCK IN</Text></Pressable><View style={{ gap: 9 }}>{stockIns.map((record) => { const quantity = record.lines.reduce((sum, line) => sum + line.quantity, 0); const cost = record.lines.reduce((sum, line) => sum + line.quantity * line.unitCost, 0); return <Pressable key={record.id} onPress={() => router.push(`/stock/in/${record.id}` as never)} style={({ pressed }) => [{ backgroundColor: colors.card, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 14 }, pressed && { opacity: 0.75 }]}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 13 }}>{record.stockInNumber}</Text><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 10, marginTop: 4 }}>{record.date} · {locations.find((location) => location.id === record.locationId)?.name}</Text></View><Text style={{ color: record.status === 'POSTED' ? colors.success : colors.warning, fontFamily: 'Inter_700Bold', fontSize: 10 }}>{record.status}</Text></View><View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 14 }}><View><Text style={{ color: colors.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 11 }}>{suppliers.find((supplier) => supplier.id === record.supplierId)?.name ?? 'Supplier'}</Text><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 3 }}>{record.lines.length} product(s) · {quantity} total units</Text></View><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 14 }}>K {cost.toLocaleString()}</Text></View><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 10 }}>{record.lines.map((line) => products.find((product) => product.id === line.productId)?.name).join(', ')}</Text></Pressable>})}</View>{stockIns.length === 0 && <View style={{ alignItems: 'center', paddingVertical: 55 }}><Feather name="inbox" size={26} color={colors.mutedForeground} /><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 10 }}>No stock-in records yet.</Text></View>}</Screen>;
}