import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { AppHeader } from '@/components/AppHeader';
import { Screen } from '@/components/Screen';
import { useMockStore } from '@/context/MockStoreContext';
import { locations, products } from '@/mock/data';
import { useColors } from '@/hooks/useColors';

export default function TransferHistoryScreen() {
  const colors = useColors();
  const { transfers } = useMockStore();
  return <Screen><AppHeader title="Transfer history" subtitle={`${transfers.length} local transfer records`} /><Pressable onPress={() => router.push('/stock/transfer-new' as never)} style={({ pressed }) => [{ height: 55, borderRadius: 16, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 18 }, pressed && { opacity: 0.75 }]}><Feather name="plus-circle" size={19} color={colors.white} /><Text style={{ color: colors.white, fontFamily: 'Inter_700Bold', fontSize: 14 }}>NEW TRANSFER</Text></Pressable><View style={{ gap: 9 }}>{transfers.map((record) => { const quantity = record.lines.reduce((sum, line) => sum + line.quantity, 0); return <Pressable key={record.id} onPress={() => router.push(`/stock/transfer/${record.id}` as never)} style={({ pressed }) => [{ backgroundColor: colors.card, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 14 }, pressed && { opacity: 0.75 }]}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View><Text style={{ color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 13 }}>{record.transferNumber}</Text><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 10, marginTop: 4 }}>{record.date}</Text></View><Text style={{ color: record.status === 'POSTED' ? colors.success : colors.warning, fontFamily: 'Inter_700Bold', fontSize: 10 }}>{record.status}</Text></View><View style={{ flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 15 }}><View style={{ paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: colors.background }}><Text style={{ color: colors.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 10 }}>{locations.find((location) => location.id === record.fromLocationId)?.name}</Text></View><Feather name="arrow-right" size={14} color={colors.primary} /><View style={{ paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: colors.secondary }}><Text style={{ color: colors.primary, fontFamily: 'Inter_600SemiBold', fontSize: 10 }}>{locations.find((location) => location.id === record.toLocationId)?.name}</Text></View><Text style={{ marginLeft: 'auto', color: colors.foreground, fontFamily: 'Inter_700Bold', fontSize: 12 }}>{quantity} units</Text></View><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 10 }}>{record.lines.map((line) => products.find((product) => product.id === line.productId)?.name).join(', ')}</Text></Pressable>})}</View>{transfers.length === 0 && <View style={{ alignItems: 'center', paddingVertical: 55 }}><Feather name="shuffle" size={26} color={colors.mutedForeground} /><Text style={{ color: colors.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 10 }}>No transfer records yet.</Text></View>}</Screen>;
}